name: learn-github-actions  # 이름으로 github에서 actio에 보여진다.
# trigger로 특정 브렌치에 이벤트가 발생할 때 또는 일정한 주기를 작성한다.
# 브랜치에 이벤트가 자주 발생하는 경우는 일정한 주기를 갖도록 하는 것이 좋고
# 브랜치에 이벤트가 자주 발생하지 않는다면 브랜치의 이벤트를 설정
# 빌드를 했을 때 빌드 시간보다 자주 업데이트 되면 자주 발생하는 것이다.
on:
  push:
    branches:
      - main
jobs:
  python-hello-world:
    runs-on: ubuntu-latest # 실행환경 - 운영체제
    steps:
      - uses: actions/checkout@v4 # 코드를 가져오는 것
      - uses: actions/setup-python@v2 # 실행 환경 - 프로그래밍 언어나 프레임워크
        with:
          python-version: "3.10"
      - run: python -c "print('hello world')"